# Generated by Django 5.1.7 on 2025-04-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cuisine',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='year',
        ),
    ]
