# Generated by Django 5.1.7 on 2025-04-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('reservation_time', models.DateField(auto_now=True)),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
    ]
